#!/usr/bin/env bash
#
# Copyright (c) 2017 Joyent Inc., All rights reserved.
#

if [[ -n "$TRACE" ]]; then
  export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
  set -o xtrace
fi

set -euo pipefail
IFS=$'\n\t'

AUTO_INST="auto_install.conf"
TRITON_DIST_FILE="site61.tgz"

RELEASE=
MIRROR=
MIRROR_PATH=
ISO=
ISO_DIR=
ISO_MOUNT=
ISO_LAYOUT=
ISO_CHECKSUM=
ISO_FILENAME=


usage() {
cat <<EOF

Create a custom OpenBSD ISO with the necessary packages and tooling installed
for deploying on SmartOS, Triton and the Joyent Public Cloud.

Usage:
  $0 -r <RELEASE> -m <MIRROR> -p <MIRROR_PATH> -i <ISO> -c <ISO_CHECKSUM> -d <ISO_DIR> -M <ISO_MOUNT> -l <ISO_LAYOUT> -f <ISO_FILENAME>

Example:
  $0 -r 6.1 -m ftp5.usa.openbsd.org -p /pub/OpenBSD -i install61.iso -c SHA256 -d /data/openbsd-6.1-iso -M /mnt/openbsd-6.1-iso -l /data/openbsd-custom-6.1 -f openbsd-6.1-custom.iso

OPTIONS:
  -r The desired OpenBSD release (e.g., 6.1)
  -m The mirror to use when downloading the release ISO. Do not include protocol (e.g., http://). Assumes http mirror
  -p The desired mirror path to the ISO (e.g., /pub/OpenBSD)
  -i The ISO filename
  -c The name of the checksum file for the ISO
  -d The location to save the dowloaded ISO. Must be absolute path.
  -M The mount point for the downloaded ISO
  -l The directory location for saving a copy of the ISO layout. Must be absolute path.
  -f The name to use for the custom ISO
  -h Show this message

EOF
}

while getopts "hr:m:p:i:c:d:M:l:f:" OPTION
do
  case $OPTION in
    h)
      usage
      exit 1
      ;;
    r)
      RELEASE=${OPTARG}
      ;;
    m)
      MIRROR=${OPTARG%/}
      ;;
    p)
      MIRROR_PATH=${OPTARG%/}
      ;;
    i)
      ISO=${OPTARG}
      ;;
    c)
      ISO_CHECKSUM=${OPTARG}
      ;;
    d)
      ISO_DIR=${OPTARG%/}
      ;;
    M)
      ISO_MOUNT=${OPTARG%/}
      ;;
    l)
      ISO_LAYOUT=${OPTARG%/}
      ;;
    f)
      ISO_FILENAME="./${OPTARG}"
      ;;
    ?)
      usage
      exit
      ;;
  esac
done

if [[ -z ${RELEASE} ]]; then
  echo "Error: missing release value (-r)"
  exit 1
fi

if [[ -z ${MIRROR} ]]; then
  echo "Error: missing mirror url (-m)"
  exit 1
fi

if [[ -z ${MIRROR_PATH} ]]; then
  echo "Error: missing mirror path (-p)"
  exit 1
fi

if [[ -z ${ISO} ]]; then
  echo "Error: missing ISO (-i) value"
  exit 1
fi

if [[ -z ${ISO} ]]; then
  echo "Error: missing ISO checksum (-c) value"
  exit 1
fi

if [[ -z ${ISO_DIR} ]]; then
  echo "Error: missing ISO directory (-d) value"
  exit 1
fi

if [[ -z ${ISO_MOUNT} ]]; then
  echo "Error: missing mount point directory (-M) value"
  exit 1
fi

if [[ -z ${ISO_LAYOUT} ]]; then
  echo "Error: missing DVD layout directory (-l) value"
  exit 1
fi

if [[ -z ${ISO_FILENAME} ]]; then
  echo "Error: missing custom ISO file name (-f) value"
  exit 1
fi

# Clean up ISO file if download is interrupted
trap 'rm -rf ${ISO_DIR}/${ISO}' SIGHUP SIGINT SIGTERM
# Delete Previous custom layout
trap 'rm -rf ${ISO_LAYOUT}' SIGHUP SIGINT SIGTERM

fetch_iso() {
  if [[ ! -d $ISO_DIR ]]; then
    mkdir -p $ISO_DIR
  fi

  echo "==> Fetching ${ISO_CHECKSUM}"
  curl -sS -o ${ISO_DIR}/${ISO_CHECKSUM} https://${MIRROR}${MIRROR_PATH}/${RELEASE}/amd64/${ISO_CHECKSUM}

  echo "==> Checking for local copy of $ISO..."
  if [[ -e $ISO_DIR/$ISO ]]; then
    echo "==> Found local copy of $ISO"

    echo "==> Verifying $ISO with ${ISO_CHECKSUM}"

    if [[ "$(sha256 $ISO_DIR/$ISO | cut -f2 -d= | tr -d '[:space:]')" == "$(grep "($ISO)" $ISO_DIR/${ISO_CHECKSUM} | cut -f2 -d= | tr -d '[:space:]')" ]]; then
        echo "==> Checksums match."
    else
        echo "==> Checksums don't match!"
        exit 1
    fi

  else
      echo "==> Local copy not found."
      echo "==> Fetching ISO from $MIRROR..."
      curl -sS -o ${ISO_DIR}/${ISO} https://${MIRROR}${MIRROR_PATH}/${RELEASE}/amd64/${ISO}
      echo "==> Done!"
      echo "==> ${ISO} saved to $ISO_DIR/"

      echo "==> Verifying $ISO with ${ISO_CHECKSUM}"

      if [[ "$(sha256 $ISO_DIR/$ISO | cut -f2 -d= | tr -d '[:space:]')" == "$(grep "($ISO)" $ISO_DIR/${ISO_CHECKSUM} | cut -f2 -d= | tr -d '[:space:]')" ]]; then
          echo "==> Checksums match."
      else
          echo "==> Checksums don't match!"
          exit 1
      fi
  fi
}

create_layout() {
  echo "==> Creating custom ISO Layout"
  if [[ -d $ISO_LAYOUT ]]; then
      echo "==> Previous layout $ISO_LAYOUT exists...deleting"
      rm -rf $ISO_LAYOUT
  fi
  echo "==> Creating $ISO_LAYOUT"
  mkdir -p $ISO_LAYOUT

  if [[ ! -d $ISO_MOUNT ]]; then
      echo "==> Creating $ISO_MOUNT ..."
      mkdir -p $ISO_MOUNT
  fi

  if df | grep -q $ISO_MOUNT; then
    echo "==> Unmounting previous $ISO_MOUNT..."
    umount $ISO_MOUNT
  fi

  echo "==> Mounting $ISO to $ISO_MOUNT"
  mount -t cd9660 /dev/"$(mdconfig -f $ISO_DIR/$ISO)" $ISO_MOUNT

  echo "==> Copying layout from $ISO_MOUNT to $ISO_LAYOUT"
  rsync -aq $ISO_MOUNT/ $ISO_LAYOUT

  echo "==> Copying and integrating Triton guesttools:"

  # Cleanup previous distribution file
  [[ -f $TRITON_DIST_FILE ]] && rm $TRITON_DIST_FILE

  ( cd triton-openbsd-guesttools
    tar -czpf ../${TRITON_DIST_FILE} ./etc ./lib ./usr ./install.site
  )

  cp $TRITON_DIST_FILE ${ISO_LAYOUT}/${RELEASE}/amd64/${TRITON_DIST_FILE}

  echo "==> Generating shasum for $TRITON_DIST_FILE"
  SITE_SHASUM=$(shasum -a 256 $TRITON_DIST_FILE | cut -f1 -d' ')
  echo "SHA256 ($TRITON_DIST_FILE) = $SITE_SHASUM" >> $ISO_LAYOUT/$RELEASE/amd64/SHA256

  echo "==> Copying $AUTO_INST to $ISO_LAYOUT/$RELEASE/amd64/"
  cp $AUTO_INST $ISO_LAYOUT/$RELEASE/amd64/

  echo "==> Unmounting $ISO_MOUNT"
  umount $ISO_MOUNT
}

create_newiso() {
  echo "==> Getting Volume ID for ${ISO}"
  CUSTOM_ISO_TITLE=$(isoinfo -d -i ${ISO_DIR}/${ISO} | grep "Volume id" | awk '{print $3}')
  echo "==> Volume ID is $CUSTOM_ISO_TITLE"

  echo "==> Preparing NEW ISO"
  mkisofs -J -R -no-emul-boot \
    -V "$CUSTOM_ISO_TITLE" \
    -p "Joyent" -b $RELEASE/amd64/cdboot \
    -o $ISO_FILENAME $ISO_LAYOUT
  echo "==> Custom ISO now ready: $ISO_FILENAME"
}

echo "==> ISO Build Starting!"
fetch_iso
create_layout
create_newiso
