#!/usr/local/bin/bash

# Copyright (c) 2016 Joyent Inc., All rights reserved.
# For scripts that should be run on first boot only

# load common functions and vars
. /lib/smartdc/common.lib

# Set root password if root_pw is set in the image manifest
(/lib/smartdc/set-rootpassword)

# Format disk
(/lib/smartdc/format-secondary-disk)

# Disable firstboot once all scripts are run
lib_triton_info "Disabling firstboot"
touch /lib/smartdc/.firstboot-complete-do-not-delete

exit 0
