#!/usr/local/bin/bash
#
# Copyright (c) 2016 Joyent Inc., All rights reserved.
#

. /lib/smartdc/common.lib

lib_triton_info "Retrieving metadata operator-script..."
$MDATA_GET sdc:operator-script >/var/tmp/mdata-operator-script.new
case $? in
  0)
    lib_triton_info "Metadata operator-script successfuly retrieved."
    mv /var/tmp/mdata-operator-script{.new,}
    chmod +x /var/tmp/mdata-operator-script
    ;;
  1)
    lib_triton_info "Metadata operator-script not defined."
    rm -f /var/tmp/mdata-operator-script{,.new}
    ;;
  *)
    lib_triton_fatal "Metadata couldn't be retrieved."
    ;;
esac

if [[ -x /var/tmp/mdata-operator-script ]]; then
  lib_triton_info "Executing metadata operator-script"
  /var/tmp/mdata-operator-script
  operator_script_exit=$?
  if [[ ${operator_script_exit} -gt 0 ]]; then
    lib_triton_info "WARNING: operator-script failed: exited \
      ${operator_script_exit}" >&2
  fi
fi
