#!/usr/local/bin/bash
#
# Copyright (c) 2017 Joyent Inc., All rights reserved.
#
# This script sets the password for the root user if this:
#
#  "users": [{"name": "root"}]
#
# has been set in the image manifest.
#
# This script must only be run once via firstboot. The script will first check
# /etc/master.passwd to ensure a root password is not being overwritten.

# load common functions and vars
. /lib/smartdc/common.lib

# Check /etc/master.passwd. If root pass is set, exit so we don't clobber an
# already set password. An empty password is typically represented by "*"
passset=$(awk -F: '/^root:/ { print $2 }' < /etc/master.passwd)
if [[ "$passset" != "*" && "$passset" != "*************" ]]; then
  lib_triton_fatal "The root password already set in /etc/master.passwd. Exiting."
fi

# Check if root_pw is set in meta data then use it
pass=$($MDATA_GET root_pw | encrypt -b 6)
if [[ $? -eq 0 ]] ; then
    lib_triton_info "Setting root password to value of meta-data root_pw."
    usermod -p $pass root
else
    lib_triton_info "No root password set in root_pw. Skipping."
fi

exit 0
